//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTransmit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTransmit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] curl_ca_bundle_crt_gz {
            get {
                object obj = ResourceManager.GetObject("curl_ca_bundle_crt_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] curl_exe_gz {
            get {
                object obj = ResourceManager.GetObject("curl_exe_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygev_4_dll_gz {
            get {
                object obj = ResourceManager.GetObject("cygev_4_dll_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cyggcc_s_seh_1_dll_gz {
            get {
                object obj = ResourceManager.GetObject("cyggcc_s_seh_1_dll_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygmbedcrypto_3_dll_gz {
            get {
                object obj = ResourceManager.GetObject("cygmbedcrypto_3_dll_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygpcre_1_dll_gz {
            get {
                object obj = ResourceManager.GetObject("cygpcre_1_dll_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygsodium_23_dll_gz {
            get {
                object obj = ResourceManager.GetObject("cygsodium_23_dll_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cygwin1_dll_gz {
            get {
                object obj = ResourceManager.GetObject("cygwin1_dll_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libcurl_x64_dll_gz {
            get {
                object obj = ResourceManager.GetObject("libcurl_x64_dll_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listen-address 127.0.0.1:PORT-LISTEN
        ///toggle 0
        ///forward-socks5 / 127.0.0.1:PORT-FORWARD-SOCKS5 .
        ///max-client-connections 2048
        ///activity-animation 0
        ///show-on-task-bar 0
        ///hide-console.
        /// </summary>
        internal static string privoxy_config_txt {
            get {
                return ResourceManager.GetString("privoxy_config_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] privoxy_exe_gz {
            get {
                object obj = ResourceManager.GetObject("privoxy_exe_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ss_local_exe_gz {
            get {
                object obj = ResourceManager.GetObject("ss_local_exe_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] v2ctl_exe_gz {
            get {
                object obj = ResourceManager.GetObject("v2ctl_exe_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Config file of V2Ray.
        ///{
        ///  &quot;log&quot;: {
        ///    // By default, V2Ray writes access log to stdout.
        ///    // &quot;access&quot;: &quot;/path/to/access/log/file&quot;,
        ///
        ///    // By default, V2Ray write error log to stdout.
        ///    // &quot;error&quot;: &quot;/path/to/error/log/file&quot;,
        ///
        ///    // Log level, one of &quot;debug&quot;, &quot;info&quot;, &quot;warning&quot;, &quot;error&quot;, &quot;none&quot;
        ///    &quot;loglevel&quot;: &quot;error&quot;
        ///  },
        ///
        ///  // List of inbound proxy configurations.
        ///  &quot;inbounds&quot;: [
        ///    {
        ///      // Tag of the inbound proxy. May be used for routing.
        ///      &quot;tag&quot;: &quot;socks-inbound&quot;,
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v2ray_config_json {
            get {
                return ResourceManager.GetString("v2ray_config_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] v2ray_exe_gz {
            get {
                object obj = ResourceManager.GetObject("v2ray_exe_gz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon xtransmit_off {
            get {
                object obj = ResourceManager.GetObject("xtransmit_off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon xtransmit_on {
            get {
                object obj = ResourceManager.GetObject("xtransmit_on", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
